export interface PrivacyListItem {
	lead?: string;
	text: string;
}

export type PrivacyBlock =
	| { kind: 'paragraph'; text: string }
	| { kind: 'list'; items: PrivacyListItem[] }
	| { kind: 'paragraphWithLink'; before: string; linkText: string; linkHref: string; after: string };

export interface PrivacySection {
	id: string;
	navLabel: string;
	title: string;
	blocks: PrivacyBlock[];
}

export const privacyMeta = {
	lastUpdated: 'July 1, 2026',
};

export const privacySections: PrivacySection[] = [
	{
		id: 'overview',
		navLabel: 'Overview',
		title: 'Overview',
		blocks: [
			{
				kind: 'paragraph',
				text: 'MarketDay ("we", "us") connects shoppers with local market vendors so orders can be reserved ahead and collected in person. This policy explains what information we collect through our app and website, why we collect it, and the choices you have. By using MarketDay, you agree to the practices described here.',
			},
		],
	},
	{
		id: 'collect',
		navLabel: 'Information we collect',
		title: 'Information we collect',
		blocks: [
			{
				kind: 'paragraph',
				text: 'We collect information you give us directly, information generated by using the app, and a small amount from third parties:',
			},
			{
				kind: 'list',
				items: [
					{ lead: 'Account details', text: 'name, phone number, and email when you sign up or place an order.' },
					{ lead: 'Order activity', text: 'items reserved, collection times, and communications with vendors.' },
					{ lead: 'Device & usage data', text: 'app version, device type, crash logs, and general usage patterns.' },
					{ lead: 'Location', text: 'approximate or precise location, only with your permission, to show nearby markets.' },
					{ lead: 'Vendor business details', text: 'for vendor accounts: stall name, market affiliations, and payout information.' },
				],
			},
		],
	},
	{
		id: 'use',
		navLabel: 'How we use it',
		title: 'How we use your information',
		blocks: [
			{ kind: 'paragraph', text: 'We use the information above to:' },
			{
				kind: 'list',
				items: [
					{ text: 'Process and confirm pre-orders between shoppers and vendors.' },
					{ text: 'Show relevant markets and vendors near you.' },
					{ text: 'Send order updates, collection reminders, and account notices.' },
					{ text: 'Improve app performance and fix bugs.' },
					{ text: 'Detect and prevent fraud or abuse of the platform.' },
				],
			},
			{
				kind: 'paragraph',
				text: 'We do not sell your personal information, and we do not use your order history to sell you ads on other platforms.',
			},
		],
	},
	{
		id: 'location',
		navLabel: 'Location data',
		title: 'Location data',
		blocks: [
			{
				kind: 'paragraph',
				text: "Location access is optional and only used to sort markets by distance and estimate travel time to collection. You can disable location access at any time in your device settings — MarketDay will still work, you'll just need to search by area or market name instead.",
			},
		],
	},
	{
		id: 'orders',
		navLabel: 'Orders & payments',
		title: 'Orders & payments',
		blocks: [
			{
				kind: 'paragraph',
				text: "MarketDay does not process in-app payments — you pay the vendor directly at the stall. We share only what's needed to fulfil your order (your name, order details, and collection time) with the vendor you're ordering from. Vendor payout information is processed through our payments partner and is never visible to shoppers.",
			},
		],
	},
	{
		id: 'sharing',
		navLabel: 'Sharing your data',
		title: 'Sharing your data',
		blocks: [
			{ kind: 'paragraph', text: 'We share information only in these situations:' },
			{
				kind: 'list',
				items: [
					{ text: 'With the vendor you place an order with, to fulfil that order.' },
					{
						text: 'With service providers who help us run the app (hosting, analytics, customer support), under contracts that limit their use of your data.',
					},
					{ text: 'If required by law, regulation, or a valid legal request.' },
					{ text: "In connection with a merger or acquisition, in which case you'll be notified." },
				],
			},
		],
	},
	{
		id: 'retention',
		navLabel: 'Data retention',
		title: 'Data retention',
		blocks: [
			{
				kind: 'paragraph',
				text: "We keep account and order data for as long as your account is active, and for a limited period afterward to meet accounting and legal obligations. You can request deletion of your account at any time; we'll remove personal data except where we're required to retain it by law.",
			},
		],
	},
	{
		id: 'rights',
		navLabel: 'Your rights',
		title: 'Your rights',
		blocks: [
			{ kind: 'paragraph', text: 'Depending on where you live, you may have the right to:' },
			{
				kind: 'list',
				items: [
					{ text: 'Access a copy of the personal data we hold about you.' },
					{ text: 'Correct inaccurate or incomplete data.' },
					{ text: 'Request deletion of your data.' },
					{ text: 'Object to or restrict certain processing.' },
					{ text: 'Withdraw consent for location or marketing at any time.' },
				],
			},
			{
				kind: 'paragraphWithLink',
				before: 'To exercise any of these, email ',
				linkText: 'privacy@marketday.app',
				linkHref: 'mailto:privacy@marketday.app',
				after: ". We'll respond within 30 days.",
			},
		],
	},
	{
		id: 'cookies',
		navLabel: 'Cookies',
		title: 'Cookies',
		blocks: [
			{
				kind: 'paragraph',
				text: 'Our website uses essential cookies to keep you signed in and remember basic preferences, and limited analytics cookies to understand how the site is used. You can control cookies through your browser settings; blocking them may affect some site features.',
			},
		],
	},
	{
		id: 'children',
		navLabel: "Children's privacy",
		title: "Children's privacy",
		blocks: [
			{
				kind: 'paragraph',
				text: "MarketDay is not directed at children under 16, and we do not knowingly collect personal information from them. If you believe a child has provided us with personal data, contact us and we'll remove it.",
			},
		],
	},
	{
		id: 'changes',
		navLabel: 'Changes to this policy',
		title: 'Changes to this policy',
		blocks: [
			{
				kind: 'paragraph',
				text: 'We may update this policy as our service evolves. If we make material changes, we\'ll notify you in the app or by email before they take effect. The "last updated" date at the top always reflects the latest version.',
			},
		],
	},
	{
		id: 'contact',
		navLabel: 'Contact us',
		title: 'Contact us',
		blocks: [],
	},
];

export const privacyContact = {
	email: 'privacy@marketday.app',
	postalAddress: 'MarketDay, 14 Dame Street, Dublin 2, D02 X285, Ireland',
};
